name: Build Kivy APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install system dependencies and JDK
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          git \
          zip \
          unzip \
          build-essential \
          libffi-dev \
          libssl-dev \
          liblzma-dev \
          zlib1g-dev \
          python3-pip \
          python3-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          openjdk-17-jdk

    - name: Install Autotools and Libtool support
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          autoconf \
          automake \
          libtool \
          libltdl-dev \
          pkg-config

    - name: Install Android SDK Command-line Tools
      # ... (كما في ملفك الأصلي) ...

    - name: Install Android SDK components and NDK
      # ... (كما في ملفك الأصلي) ...

    - name: Link Android SDK for Buildozer
      # ... (كما في ملفك الأصلي) ...

    - name: Accept Android SDK Licenses
      run: |
        yes | $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses

    - name: Install/Upgrade Buildozer and Cython
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install cython
        pip install --upgrade buildozer

    - name: Clean previous build artifacts
      run: |
        buildozer clean || echo "Nothing to clean"

    - name: Build APK with Buildozer
      run: |
        echo "Starting Buildozer build..."
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-apk
        path: bin/*.apk
