# Workflow name
name: Build Kivy APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install system dependencies and JDK
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          git \
          zip \
          unzip \
          build-essential \
          libffi-dev \
          libssl-dev \
          liblzma-dev \
          zlib1g-dev \
          python3-pip \
          python3-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          openjdk-17-jdk
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

    - name: Install Autotools and Libtool support
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          autoconf \
          automake \
          libtool \
          libltdl-dev \
          pkg-config
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

    - name: Install Android SDK Command-line Tools
      env:
        CMDLINE_TOOLS_VERSION: "11076708"
        ANDROID_SDK_ROOT: "${{ github.workspace }}/android-sdk"
      run: |
        mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
        wget -q "https://dl.google.com/android/repository/commandlinetools-linux-${CMDLINE_TOOLS_VERSION}_latest.zip" -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d "${ANDROID_SDK_ROOT}/cmdline-tools"
        rm cmdline-tools.zip

        # Normalize into cmdline-tools/latest
        mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools/latest"
        if [ -d "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools" ]; then
          mv "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools/"* "${ANDROID_SDK_ROOT}/cmdline-tools/latest/"
          rm -rf "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools"
        else
          find "${ANDROID_SDK_ROOT}/cmdline-tools" -maxdepth 1 -mindepth 1 ! -name latest -exec mv -t "${ANDROID_SDK_ROOT}/cmdline-tools/latest/" {} +
        fi

        echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}" >> $GITHUB_ENV
        echo "PATH=${PATH}:${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_ENV

    - name: Install Android SDK components and NDK
      env:
        ANDROID_PLATFORM_VERSION: "34"
        ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
        ANDROID_NDK_VERSION: "25.2.9519653"
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-${ANDROID_PLATFORM_VERSION}" "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "ndk;${ANDROID_NDK_VERSION}"
        echo "ANDROID_NDK_HOME=${{ github.workspace }}/android-sdk/ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_ENV

    - name: Link Android SDK for Buildozer
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        rm -rf $HOME/.buildozer/android/platform/android-sdk
        ln -s "${{ github.workspace }}/android-sdk" $HOME/.buildozer/android/platform/android-sdk

    - name: Link sdkmanager for Buildozer expected path
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        ln -sf "${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin/sdkmanager" \
               $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Accept Android SDK Licenses
      run: |
        yes | $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses

    - name: Install/Upgrade Buildozer and Cython
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install cython
        pip install --upgrade buildozer

    - name: Clean previous build artifacts
      run: |
        buildozer clean || echo "Nothing to clean"

    - name: Build APK with Buildozer
      run: |
        echo "Starting Buildozer build..."
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-apk
        path: bin/*.apk
